config/routes.rb
Rails.application.routes.draw do
 resources :activities
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :employees
   root 'home#index'
    

end

app/models/activity.rb
class Activity < ActiveRecord::Base
belongs_to :employee
belongs_to :task
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :activities,:dependent => :destroy
  has_many :tasks,:dependent => :destroy       
end

app/models/task.rb
class Task < ActiveRecord::Base
has_many :activities,:dependent => :destroy
belongs_to :employee	
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
	#before_action :set_activity, only: [:show, :edit, :update, :destroy]
	#before_action :set_movie
	#before_action :authenticate_employee!
	def new
		@activity = Activity.new
	end
	def index
		@activities = current_employee.activities
	end
	def create
		@activity = Activity.new(allow_params)
		@activity.employee_id = current_employee.id
		if @activity.save
			redirect_to @activity
		else
			render 'new'
		end

	end
	
    def edit
    end

    def update
    	@activity.update(allow_params)
    end
    def destroy
    	@activity.destroy
    end
    
	private
	def set_activity
		@activity = Activity.find(params[:id])
		end
		
	def allow_params
		params.require(:activity).permit(:date, :description, :task_id, :employee_id)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #before_action :authenticate_employee!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/activities/_form.html.erb
<%= form_for([@activity]) do |f| %>
 
  
   <div class="field">
    <%= f.label :date %><br>
    <%= f.date_field :date %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
  <%= link_to "back" , @activity%>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing Activities</h1>

<%= render 'form' %>

<%#= link_to "back" , movie_path(@movie) %>

app/views/activities/index.html.erb
<h1>Listing activities</h1>
<% @activities.each do |activity| %>
<tr>
<td><strong>Date: </strong><%= current_employee.activity.date %><br></td>
<td><strong>Description: </strong><%= current_employee.activity.description %></td>
<td><%= link_to 'Edit', edit_activity_path %></td>
<td><%= link_to 'Destroy', activity_path(activity),
              method: :delete,
            data: { confirm: 'Are you sure?' } %></td>
          </tr>
<% end %>

<%#= link_to 'New activity', new_activity_path %>
<%#= link_to 'Edit', edit_activity_path %>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form' %>
<%#= link_to "back" , @activity %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
      <div class="header" id="header">
        <h1 class="site_title" id="site_title">Sample</h1>
        <ul class="header-item tabs" id="tabs">
           
         <%if  employee_signed_in? and current_employee.role == "Employee"%>
          <li><%= link_to  "New activity",   new_activity_path %></li>
          <li><%= link_to  "Show my activities",  @activity %></li>
          <li><%= link_to('Logout', destroy_employee_session_path, :method => :delete) %></li>
          <%else%>
          <li><%= link_to('Login', new_employee_session_path)%> </li>
          <li id="activities"><a href="/admin/activities">Activities</a></li>
          <li id="admin_users"><a href="/admin/admin_users">Admin Login</a></li>
          <li id="tasks"><a href="/admin/tasks">Tasks</a></li>
          <li id="tasks"><a href="/admin/employees">Employees</a></li>
           
          <%end%>
        </ul>
        
      </div>
<%= yield %>


</body>
</html>